 i8* @CAT_new
 i8* @CAT_new
 i8* @CAT_new
 void @CAT_set
 void @CAT_set
 void @CAT_set
 i8* @CAT_new
 void @CAT_set
 void @CAT_set
 void @CAT_set
 i8* @CAT_new
 void @CAT_set
 void @CAT_set
 void @CAT_set
 i8* @CAT_new
 void @CAT_set
 void @CAT_set
 void @CAT_set
 i8* @CAT_new
 void @CAT_set
 void @CAT_set
 void @CAT_set
 i8* @CAT_new
 i8* @CAT_new
 void @CAT_set
 void @CAT_set
 void @CAT_set
 i64 @CAT_variables
 i64 @CAT_cost
