 i8* @CAT_new
 i64 @CAT_get
 i8* @CAT_new
 i64 @CAT_get
 i8* @CAT_new
 void @CAT_sub
 void @CAT_add
 i64 @CAT_get
 void @CAT_set
 i64 @CAT_get
 void @CAT_destroy
 void @CAT_execution
 i64 @CAT_variables
 i64 @CAT_cost
